---
title: "Scatterplots"
output: 
  html_document:
    toc: true
    number_sections: true
    toc_depth: 4
    toc_float: 
      collapsed: false
      smooth_scroll: false
---

# Old Faithful Geyser
```{r}

library(ggplot2)
library(ggExtra)
head(faithful)

p = ggplot(faithful, 
           aes(x = waiting, y = eruptions)) + 
  geom_point(alpha = .5,
             size = 3,
             position = "jitter") +
  theme_classic() +
  theme(title = element_text(face = "bold"))

p   

ggMarginal(p) # add marginal density plot
```



# Iris flowers
## Plot 1

```{r}
ggplot(iris, 
       aes(Sepal.Length, y = Sepal.Width, color = Species)) + 
  geom_count(alpha = .6) + # use point size to show data density (overcome overlaping)
  theme_classic() +
  labs(title = "Edgar Anderson's Iris Data") +
  theme(title = element_text(face = "bold"))
```


## Plot 2

```{r}
library(ggplot2)
head(iris)
ggplot(iris, 
       aes(x = Sepal.Length, y = Sepal.Width, 
           color = Petal.Length, size = Petal.Width)) + 
  geom_point(position = position_jitter(.2, .2), alpha = .6) + # add small random noise to dots' position to avoid overlap
  geom_smooth(method = "lm", color = "black", se = F, size = .5) +
  facet_wrap(~Species) + # facet based on species 
  
  # polish up
  theme_bw() +
  scale_color_continuous(low = "steelblue", high = "black") + # control colorbar for Petal.Length
  theme(title = element_text(face = "bold"),
        axis.title =  element_text(color = "firebrick", face = "bold"),
        axis.text = element_text(color = "firebrick"),
        strip.background = element_blank(), 
        strip.text = element_text(face = "bold", color = "firebrick", size = 12)) +
  labs(title = "Edgar Anderson's Iris Data")
```


# Diamonds 
```{r}
library(ggplot2)
head(diamonds)
dim(diamonds)

ggplot(diamonds, 
       aes(x = carat, y = price, color = cut)) + 
  geom_point(alpha = .4, shape = ".") + # "shape = "." and transparency set to .4 decrease overlap 
  geom_smooth(method = "lm", se = F, size = .6, linetype = "dashed") + # regression
  
  # polish up
  scale_color_brewer(palette = "Set1") + 
  theme_bw() + 
  theme(legend.position = c(.8, .2), 
        title = element_text(face = "bold")) +
  coord_cartesian(xlim = c(0, 4), ylim = c(0, 20000)) + # zoom in 
  labs(title = "Prices of 50,000 round cut diamonds")
```


# Cars
```{r, fig.width=10, fig.height=8}
library(ggplot2)
library(ggrepel)
library(ggExtra)
p = ggplot(mtcars, 
           aes(x = wt, y = mpg, 
               color = factor(cyl), shape = factor(am))) + # use of "factor()" change cyl and am from continuous to discrete variables; particularly important since "shape" is discrete
  geom_point() +
  geom_smooth(aes(group = cyl), method = "lm", se = F, linetype = "dashed") + # regression line. specification of "aes(group = cyl)" ensures grouping based on cylinder (cyl) number alone; if not specified, inheriting aesthetic from above, regression is performed  based on combinations of cyl and auto/manual transmission (am)
  geom_text_repel(aes(label = rownames(mtcars)), size = 3) + # add car names, avoiding overlap
  
  # polish up
  theme_classic() + 
  theme(legend.position = c(.8, .7), 
        title = element_text(face = "bold")) +
  stat_ellipse(aes(group = cyl), linetype = "dotted") + # add distribution ellipse
  labs(x = "Weight (1000 lbs)", y = "Miles/(US) gallon")
p  

ggMarginal(p, type = "density", size = 10, groupColour = T, groupFill = T, alpha = .2) # add marginal density plot
```



# Mammals  
```{r}
library(ggplot2)
library(MASS)
ggplot(mammals, 
       aes(x = body, y = brain)) + geom_point() +
  geom_smooth(method = "lm", fill = "firebrick", color = "firebrick", alpha = .2, size = .5) +
  scale_x_log10() + 
  scale_y_log10() + # log transform axis
  
  # polish up
  annotation_logticks() +  # add log10 marks
  theme_bw() +
  labs(title = "Attributes of Animals data") +
  theme(title = element_text(face = "bold"))
```


# New york flight 
```{r, message=F, warning=F, fig.height=9, fig.width=10}
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(nycflights13)

theme_set(theme_bw() + 
            theme(title = element_text(colour = "black", face = "bold"),
                  axis.text = element_text(colour = "black", face = "bold"),
                  legend.text = element_text(colour = "black", face = "bold"),
                  legend.title = element_text(colour = "black", face = "bold")))

planes %>% 
  ggplot(aes(x = year, y = seats, color = engine)) +
  geom_count(alpha = .4, 
             position = position_jitter(0, 10)) +
  scale_x_continuous(breaks = seq(1960, 2010, by = 10)) +
  scale_color_brewer(palette = "Dark2", "Engine type") +
  scale_size(range = c(4, 14), "Dot density") +
  theme(legend.position = c(.2, .7)) +
  labs(title = "Plane metadata")
```

